version: '3'

rpc:
  listen: tcp://127.0.0.1:6001

metrics:
  address: 0.0.0.0:2112

server:
  command: 'php app.php'
  relay: pipes
  on_init:
    command: "php app.php register:modules"

logs:
  mode: ${RR_LOG_MODE:-production}
  encoding: ${RR_LOG_ENCODING:-json}
  level: ${RR_LOG_LEVEL:-warn}
  channels:
    http:
      level: ${RR_LOG_HTTP_LEVEL:-warn}
    tcp:
      level: ${RR_LOG_TCP_LEVEL:-warn}
    jobs:
      level: ${RR_LOG_JOBS_LEVEL:-warn}
    centrifuge:
      level: ${RR_LOG_CENTRIFUGE_LEVEL:-warn}
    server:
      level: ${RR_LOG_SERVER_LEVEL:-warn}
    service:
      level: ${RR_LOG_SERVICE_LEVEL:-warn}
    smtp:
      level: ${RR_LOG_SMTP_LEVEL:-warn}
    var-dumper:
      level: ${RR_LOG_VAR_DUMPER_LEVEL:-warn}

http:
  address: 127.0.0.1:8082
  middleware: [ "headers" ]
  headers:
    cors:
      allowed_origin: ${RR_HTTP_ALLOWED_ORIGIN:-*}
      allowed_headers: ${RR_HTTP_ALLOWED_HEADERS:-*}
      allowed_methods: "GET,POST,PUT,DELETE"
      allow_credentials: ${RR_HTTP_ALLOW_CREDENTIALS:-true}
      exposed_headers: "Cache-Control,Content-Language,Content-Type,Expires,Last-Modified,Pragma"
      max_age: 600
  pool:
    num_workers: ${RR_HTTP_NUM_WORKERS:-1}

tcp:
  servers:
    monolog:
      addr: ${RR_TCP_MONOLOG_ADDR:-:9913}
      delimiter: "\n"
  read_buf_size: ${RR_TCP_READ_BUF_SIZE:-50485760}
  pool:
    num_workers: ${RR_TCP_NUM_WORKERS:-1}

kv:
  local:
    driver: memory
    config: { }

jobs:
  consume:
    - events
  pipelines:
    events:
      driver: memory
      config:
        priority: 10
        prefetch: 10
  pool:
    num_workers: ${RR_JOBS_NUM_WORKERS:-1}

smtp:
  addr: ${RR_SMTP_ADDR:-:1025}
  hostname: "buggregator.local"
  jobs:
    pipeline: events

var-dumper:
  addr: ${RR_VAR_DUMPER_ADDR:-:9912}
  max_message_size: ${RR_TCP_READ_BUF_SIZE:-50485760}
  jobs:
    pipeline: events

service:
  nginx:
    service_name_in_log: true
    remain_after_exit: true
    restart_sec: 5
    command: "/usr/sbin/nginx"
  centrifuge:
    service_name_in_log: true
    remain_after_exit: true
    restart_sec: 5
    command: "./bin/centrifugo --config=centrifugo.json"
  dolt:
    service_name_in_log: true
    remain_after_exit: true
    restart_sec: 5
    command: "./bin/dolt sql-server --data-dir=.db"

centrifuge:
  proxy_address: ${RR_CENTRIFUGE_PROXY_ADDRESS}
  grpc_api_address: ${RR_CENTRIFUGE_GRPC_API_ADDRESS}
  pool:
    num_workers: ${RR_CENTRIFUGE_NUM_WORKERS:-2}