version: '2.7'

rpc:
  listen: tcp://127.0.0.1:6001

server:
  command: 'php app.php'
  relay: pipes

logs:
  level: info

http:
  address: 127.0.0.1:8082
  middleware: [ "headers" ]
  headers:
    cors:
      allowed_origin: "*"
      allowed_headers: "*"
      allowed_methods: "GET,POST,PUT,DELETE"
      allow_credentials: true
      exposed_headers: "Cache-Control,Content-Language,Content-Type,Expires,Last-Modified,Pragma"
      max_age: 600
  pool:
    num_workers: 2

tcp:
  servers:
    monolog:
      addr: 127.0.0.1:9913
      delimiter: "\n"
    var-dumper:
      addr: 127.0.0.1:9912
      delimiter: "\n"
  pool:
    num_workers: 2

kv:
  events:
    driver: memory
    config: { }

service:
  reverse-proxy:
    service_name_in_log: true
    remain_after_exit: true
    restart_sec: 1
    command: "./bin/traefik --configFile=traefik.yaml"
  centrifuge:
    service_name_in_log: true
    remain_after_exit: true
    restart_sec: 1
    command: "./bin/centrifugo --config=centrifugo.json"

centrifuge:
  proxy_address: "tcp://127.0.0.1:10001"
  grpc_api_address: "tcp://127.0.0.1:10000"
  pool:
    reset_timeout: 10
    num_workers: 2

fileserver:
  address: 127.0.0.1:8083
  stream_request_body: true
  serve:
    - prefix: "/"
      root: "frontend/dist"
      compress: true
