CREATE TABLE IF NOT EXISTS profiles (
    uuid TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    cpu INTEGER NOT NULL DEFAULT 0,
    wt INTEGER NOT NULL DEFAULT 0,
    ct INTEGER NOT NULL DEFAULT 0,
    mu INTEGER NOT NULL DEFAULT 0,
    pmu INTEGER NOT NULL DEFAULT 0
);
