<?php

declare(strict_types=1);

namespace Database\Factory\Partials;

use Spiral\RoadRunnerBridge\Http\Dispatcher;
use Nyholm\Psr7\ServerRequest;
use Spiral\Debug\State;
use Spiral\Bootloader\DebugBootloader;
use Spiral\Telemetry\Span;
use Nyholm\Psr7\Stream;
use Nyholm\Psr7\Response;
use Spiral\Telemetry\Span\Status;
trait ProfilerType
{
    public static function getProfilerPayload(): array
    {
        return [
            'tags' => [
                'php' => '8.2.5',
                'dispatcher' => Dispatcher::class,
                'method' => 'GET',
                'url' => 'http://127.0.0.1:8080/',
                'route' => null,
                'uri' => 'http://127.0.0.1:8080/',
            ],
            'app_name' => 'My super app',
            'hostname' => 'Localhost',
            'date' => 1714289301,
            'peaks' => [
                'ct' => 1,
                'wt' => 211999,
                'cpu' => 82952,
                'mu' => 2614696,
                'pmu' => 1837832,
            ],
            'edges' => [
                'e1' => [
                    'caller' => null,
                    'callee' => 'main()',
                    'cost' => [
                        'ct' => 1,
                        'wt' => 211999,
                        'cpu' => 82952,
                        'mu' => 2614696,
                        'pmu' => 1837832,
                        'p_cpu' => 100,
                        'p_mu' => 100,
                        'p_pmu' => 100,
                        'p_wt' => 100,
                    ],
                ],
                'e2' => [
                    'caller' => 'main()',
                    'callee' => ServerRequest::class . '::getAttribute',
                    'cost' => [
                        'd_cpu' => 82950,
                        'd_wt' => 211997,
                        'd_mu' => 2614144,
                        'd_pmu' => 1837832,
                        'ct' => 1,
                        'wt' => 2,
                        'cpu' => 2,
                        'mu' => 552,
                        'pmu' => 0,
                        'p_cpu' => 0,
                        'p_mu' => 0.02,
                        'p_pmu' => 0,
                        'p_wt' => 0,
                    ],
                ],
                'e3' => [
                    'caller' => 'main()',
                    'callee' => State::class . '::getTags',
                    'cost' => [
                        'd_cpu' => 82951,
                        'd_wt' => 211999,
                        'd_mu' => 2614160,
                        'd_pmu' => 1837832,
                        'ct' => 1,
                        'wt' => 0,
                        'cpu' => 1,
                        'mu' => 536,
                        'pmu' => 0,
                        'p_cpu' => 0,
                        'p_mu' => 0.02,
                        'p_pmu' => 0,
                        'p_wt' => 0,
                    ],
                ],
                'e4' => [
                    'caller' => 'main()',
                    'callee' => DebugBootloader::class . '::state',
                    'cost' => [
                        'd_cpu' => 82855,
                        'd_wt' => 211903,
                        'd_mu' => 2604496,
                        'd_pmu' => 1837832,
                        'ct' => 1,
                        'wt' => 96,
                        'cpu' => 97,
                        'mu' => 10200,
                        'pmu' => 0,
                        'p_cpu' => 0.12,
                        'p_mu' => 0.39,
                        'p_pmu' => 0,
                        'p_wt' => 0.05,
                    ],
                ],
                'e5' => [
                    'caller' => 'main()',
                    'callee' => Span::class . '::setStatus',
                    'cost' => [
                        'd_cpu' => 82949,
                        'd_wt' => 211997,
                        'd_mu' => 2614064,
                        'd_pmu' => 1837832,
                        'ct' => 1,
                        'wt' => 2,
                        'cpu' => 3,
                        'mu' => 632,
                        'pmu' => 0,
                        'p_cpu' => 0,
                        'p_mu' => 0.02,
                        'p_pmu' => 0,
                        'p_wt' => 0,
                    ],
                ],
                'e6' => [
                    'caller' => 'main()',
                    'callee' => Stream::class . '::getSize',
                    'cost' => [
                        'd_cpu' => 82951,
                        'd_wt' => 211999,
                        'd_mu' => 2614160,
                        'd_pmu' => 1837832,
                        'ct' => 1,
                        'wt' => 0,
                        'cpu' => 1,
                        'mu' => 536,
                        'pmu' => 0,
                        'p_cpu' => 0,
                        'p_mu' => 0.02,
                        'p_pmu' => 0,
                        'p_wt' => 0,
                    ],
                ],
                'e7' => [
                    'caller' => 'main()',
                    'callee' => Response::class . '::getBody',
                    'cost' =>
                        [
                            'd_cpu' => 82951,
                            'd_wt' => 211998,
                            'd_mu' => 2614160,
                            'd_pmu' => 1837832,
                            'ct' => 1,
                            'wt' => 1,
                            'cpu' => 1,
                            'mu' => 536,
                            'pmu' => 0,
                            'p_cpu' => 0,
                            'p_mu' => 0.02,
                            'p_pmu' => 0,
                            'p_wt' => 0,
                        ],
                ],
                'e8' => [
                    'caller' => 'main()',
                    'callee' => Response::class . '::getHeaderLine',
                    'cost' => [
                        'd_cpu' => 82948,
                        'd_wt' => 211996,
                        'd_mu' => 2614144,
                        'd_pmu' => 1837832,
                        'ct' => 1,
                        'wt' => 3,
                        'cpu' => 4,
                        'mu' => 552,
                        'pmu' => 0,
                        'p_cpu' => 0,
                        'p_mu' => 0.02,
                        'p_pmu' => 0,
                        'p_wt' => 0,
                    ],
                ],
                'e9' => [
                    'caller' => 'main()',
                    'callee' => Span::class . '::setAttribute',
                    'cost' => [
                        'd_cpu' => 82949,
                        'd_wt' => 211997,
                        'd_mu' => 2613768,
                        'd_pmu' => 1837832,
                        'ct' => 2,
                        'wt' => 2,
                        'cpu' => 3,
                        'mu' => 928,
                        'pmu' => 0,
                        'p_cpu' => 0,
                        'p_mu' => 0.04,
                        'p_pmu' => 0,
                        'p_wt' => 0,
                    ],
                ],
                'e10' => [
                    'caller' => 'main()',
                    'callee' => Response::class . '::getStatusCode',
                    'cost' => [
                        'd_cpu' => 82951,
                        'd_wt' => 211998,
                        'd_mu' => 2614144,
                        'd_pmu' => 1837832,
                        'ct' => 2,
                        'wt' => 1,
                        'cpu' => 1,
                        'mu' => 552,
                        'pmu' => 0,
                        'p_cpu' => 0,
                        'p_mu' => 0.02,
                        'p_pmu' => 0,
                        'p_wt' => 0,
                    ],
                ],
                'e11' => [
                    'caller' => 'main()',
                    'callee' => 'App\\Middleware\\LocaleSelector::process',
                    'cost' => [
                        'd_cpu' => 245,
                        'd_wt' => 247,
                        'd_mu' => 14344,
                        'd_pmu' => 0,
                        'ct' => 1,
                        'wt' => 211752,
                        'cpu' => 82707,
                        'mu' => 2600352,
                        'pmu' => 1837832,
                        'p_cpu' => 99.7,
                        'p_mu' => 99.45,
                        'p_pmu' => 100,
                        'p_wt' => 99.88,
                    ],
                ],
                'e12' => [
                    'caller' => 'App\\Middleware\\LocaleSelector::process',
                    'callee' => Span::class . '::setStatus',
                    'cost' => [
                        'd_cpu' => 82701,
                        'd_wt' => 211747,
                        'd_mu' => 2599040,
                        'd_pmu' => 1837832,
                        'ct' => 1,
                        'wt' => 5,
                        'cpu' => 6,
                        'mu' => 1312,
                        'pmu' => 0,
                        'p_cpu' => 0.01,
                        'p_mu' => 0.05,
                        'p_pmu' => 0,
                        'p_wt' => 0,
                    ],
                ],
                'e13' => [
                    'caller' => Span::class . '::setStatus',
                    'callee' => Status::class . '::__construct',
                    'cost' => [
                        'd_cpu' => 3,
                        'd_wt' => 2,
                        'd_mu' => 728,
                        'd_pmu' => 0,
                        'ct' => 2,
                        'wt' => 3,
                        'cpu' => 3,
                        'mu' => 584,
                        'pmu' => 0,
                        'p_cpu' => 0,
                        'p_mu' => 0.02,
                        'p_pmu' => 0,
                        'p_wt' => 0,
                    ],
                ],
                'e14' => [
                    'caller' => 'App\\Middleware\\LocaleSelector::process',
                    'callee' => Stream::class . '::getSize',
                    'cost' => [
                        'd_cpu' => 82691,
                        'd_wt' => 211737,
                        'd_mu' => 2596728,
                        'd_pmu' => 1837832,
                        'ct' => 1,
                        'wt' => 15,
                        'cpu' => 16,
                        'mu' => 3624,
                        'pmu' => 0,
                        'p_cpu' => 0.02,
                        'p_mu' => 0.14,
                        'p_pmu' => 0,
                        'p_wt' => 0.01,
                    ],
                ],
                'e15' => [
                    'caller' => Stream::class . '::getSize',
                    'callee' => Stream::class . '::getUri',
                    'cost' => [
                        'd_cpu' => 8,
                        'd_wt' => 7,
                        'd_mu' => 2384,
                        'd_pmu' => 0,
                        'ct' => 1,
                        'wt' => 8,
                        'cpu' => 8,
                        'mu' => 1240,
                        'pmu' => 0,
                        'p_cpu' => 0.01,
                        'p_mu' => 0.05,
                        'p_pmu' => 0,
                        'p_wt' => 0,
                    ],
                ],
                'e16' => [
                    'caller' => Stream::class . '::getUri',
                    'callee' => Stream::class . '::getMetadata',
                    'cost' =>
                        [
                            'd_cpu' => 3,
                            'd_wt' => 4,
                            'd_mu' => -488,
                            'd_pmu' => 0,
                            'ct' => 1,
                            'wt' => 4,
                            'cpu' => 5,
                            'mu' => 1728,
                            'pmu' => 0,
                            'p_cpu' => 0.01,
                            'p_mu' => 0.07,
                            'p_pmu' => 0,
                            'p_wt' => 0,
                        ],
                ],
                'e17' => [
                    'caller' => 'App\\Middleware\\LocaleSelector::process',
                    'callee' => Response::class . '::getBody',
                    'cost' => [
                        'd_cpu' => 82706,
                        'd_wt' => 211751,
                        'd_mu' => 2599784,
                        'd_pmu' => 1837832,
                        'ct' => 1,
                        'wt' => 1,
                        'cpu' => 1,
                        'mu' => 568,
                        'pmu' => 0,
                        'p_cpu' => 0,
                        'p_mu' => 0.02,
                        'p_pmu' => 0,
                        'p_wt' => 0,
                    ],
                ],
                'e18' => [
                    'caller' => 'App\\Middleware\\LocaleSelector::process',
                    'callee' => Response::class . '::getHeaderLine',
                    'cost' => [
                        'd_cpu' => 82701,
                        'd_wt' => 211746,
                        'd_mu' => 2599136,
                        'd_pmu' => 1837832,
                        'ct' => 1,
                        'wt' => 6,
                        'cpu' => 6,
                        'mu' => 1216,
                        'pmu' => 0,
                        'p_cpu' => 0.01,
                        'p_mu' => 0.05,
                        'p_pmu' => 0,
                        'p_wt' => 0,
                    ],
                ],
                'e19' => [
                    'caller' => Response::class . '::getHeaderLine',
                    'callee' => Response::class . '::getHeader',
                    'cost' => [
                        'd_cpu' => 2,
                        'd_wt' => 2,
                        'd_mu' => 568,
                        'd_pmu' => 0,
                        'ct' => 2,
                        'wt' => 4,
                        'cpu' => 4,
                        'mu' => 648,
                        'pmu' => 0,
                        'p_cpu' => 0,
                        'p_mu' => 0.02,
                        'p_pmu' => 0,
                        'p_wt' => 0,
                    ],
                ],
            ],
        ];
    }
}
