on:
  pull_request: null

name: phpunit

jobs:
  phpunit:
    name: "[MySQL:${{ matrix.mysql-version }}] PHP 8.3-${{ matrix.os }}, ${{ matrix.stability }}"
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        php: [ '8.3' ]
        os: [ 'ubuntu-latest' ]
        stability: [ 'prefer-stable' ]
        mysql-version: [ '5', '8' ]

    services:
      mysql:
        image: mysql:${{ matrix.mysql-version }}
        env:
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_DATABASE: buggregator
          MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping -ppass"
          --health-interval 10s
          --health-start-period 10s
          --health-timeout 5s
          --health-retries 10

    steps:
      # General Steps
      - name: Set Git To Use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure environment
        run: |
          export COMPOSER_ROOT_VERSION=$(/usr/bin/jq --null-input --raw-output 'first(inputs["extra"]["branch-alias"])[]' composer.json)
          echo COMPOSER_ROOT_VERSION=$COMPOSER_ROOT_VERSION >> $GITHUB_ENV

      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: sockets,mongodb,pgsql,pdo_pgsql,pdo_mysql
          tools: pecl

      - name: Validate Composer
        run: composer validate

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Restore Composer Cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-${{ matrix.php }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-${{ matrix.php }}-composer

      - name: Install Dependencies
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer update --${{ matrix.stability }} --prefer-dist --no-interaction --no-progress

      # Execution mysql
      - name: Execute Tests on MySQL
        run: vendor/bin/phpunit
        env:
          PERSISTENCE_DRIVER: db
          DB_DRIVER: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: buggregator
          DB_USERNAME: root
          DB_PASSWORD: secret
